# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SunnyWuDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SunnyWuDemo

  target 'SunnyWuDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SunnyWuDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Masonry', '~> 1.0.1'
pod 'FMDB', '~> 2.6.2'

end
